name: dev auto ci process script
on: push # 아래 job을 실행시킬 상황
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전
    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
      with:
        host: ${{ secrets.SERVER_S_IP_TEST }} # 인스턴스 IP
        username: ${{ secrets.SERVER_S_USER }} # 우분투 아이디
        password: ${{ secrets.SERVER_S_PASSWORD }} # 우분투 패스워드
        port: ${{ secrets.SERVER_SSH_PORT }} # 접속포트
        script: | # 실행할 스크립트
          cd /var/work
          mkdir test100
            
